In [25]:
import os
import glob
import pandas as pd
import seaborn as sns
import random
import numpy as np
import itertools

In [23]:
materials = pd.read_csv('/Users/yuanbian/Documents/Spec_ATL/FMRI_REDBOAT_SPEC/REDBOAT/subject_materials/subject1_materials.csv')
t = list(materials[materials.Head=="CUP"].Consonant_COMP)+\
list(materials[materials.Head=="CUP"].Modifier_COMP)+\
list(materials[materials.Head=="CUP"].Consonant_LIST)+\
list(materials[materials.Head=="CUP"].Modifier_LIST)
t.sort()
t

['BLACK',
 'BLUE',
 'BOAT',
 'BROWN',
 'CROSS',
 'LAMP',
 'MTPV',
 'MTPV',
 'PINK',
 'PLANE',
 'QXSW',
 'QXSW',
 'RJDNW',
 'WVCNZ',
 'ZBXLV',
 'ZBXLV']

In [24]:
a= list(DATA_orig[DATA_orig.Word_2nd=="CUP"].Word_1st)
a.sort()
a

['BLACK',
 'BLUE',
 'BOAT',
 'BROWN',
 'CROSS',
 'LAMP',
 'MTPV',
 'MTPV',
 'PINK',
 'PLANE',
 'QXSW',
 'QXSW',
 'RJDNW',
 'WVCNZ',
 'ZBXLV',
 'ZBXLV']

In [27]:
result_dir = glob.glob('/Users/yuanbian/Downloads/josef_pilot_spec/*.csv')
dataframes = [pd.read_csv(f) for f in result_dir]
DATA_orig = pd.concat(dataframes, axis=0)
DATA_orig = DATA_orig.reset_index(drop=True)
DATA_orig = DATA_orig.reset_index()
DATA_orig = DATA_orig[DATA_orig.Condition!="FIX"][["Condition","RT", "Accuracy"]]
DATA_orig.groupby("Condition").mean()

                 RT  Accuracy
Condition
High       1.326966   0.84375
Low        1.200812   0.75000

In [258]:
result_dir = glob.glob('./*.csv')
dataframes = [pd.read_csv(f) for f in result_dir]
DATA_orig = pd.concat(dataframes, axis=0)
DATA_orig = DATA_orig.reset_index(drop=True)
DATA_orig = DATA_orig.reset_index()
#DATA_orig[DATA_orig.Condition!="FIX"][["Condition","Word_2nd"]]
DATA_orig = DATA_orig[["Condition","Noun","Question"]]
DATA_orig.groupby(["Noun"]).count()

            Condition  Question
Noun
ALCOHOL             2         2
ALGEBRA             2         2
APE                 2         2
APPLIANCE           2         2
ARM                 2         2
ARTIST              2         2
ASPIRIN             2         2
AXE                 2         2
BAGEL               2         2
BALLERINA           2         2
BOAT                2         2
BONE                2         2
BROCCOLI            2         2
BUILDING            2         2
BULLDOG             2         2
CANDY               2         2
CAPPUCCINO          2         2
CHECKERS            2         2
CHEDDAR             2         2
CHEMIST             2         2
COBRA               2         2
COIN                2         2
COKE                2         2
COMEDIAN            2         2
CONTAINER           2         2
DANCE               2         2
DAUGHTER            2         2
DESSERT             2         2
DISEASE             2         2
DOCTOR              2         2
...               ...       ...
PARENT              2         2
PASTA               2         2
PASTRY              2         2
PET                 2         2
PHONE               2         2
PINKIE              2         2
POLITICIAN          2         2
POULTRY             2         2
PURSE               2         2
RING                2         2
ROSE                2         2
ROYALTY             2         2
RUBY                2         2
SAUCE               2         2
SEASONING           2         2
SHOES               2         2
SPARROW             2         2
SPICE               2         2
SPIDER              2         2
SPORT               2         2
SPRING              2         2
TABLE               2         2
TEA                 2         2
TREE                2         2
UNCLE               2         2
UNIVERSITY          2         2
UTENSIL             2         2
WATER               2         2
WHEAT               2         2
WINE                2         2

[96 rows x 2 columns]

In [257]:
DATA_orig.iloc[:,1]#.count('COIN')

0            COIN
1          PINKIE
2           UNCLE
3        IDEOLOGY
4           PURSE
5           PASTA
6           PHONE
7         ALCOHOL
8         KETCHUP
9       CONTAINER
10         SPRING
11         SPIDER
12      BALLERINA
13        MONSTER
14           BOAT
15          DANCE
16           FROG
17        MINERAL
18           WINE
19           HERB
20            TEA
21          CANDY
22          MOUSE
23        EMOTION
24            AXE
25           GOLD
26            HAT
27        BULLDOG
28         INSECT
29       CHECKERS
30        ASPIRIN
31     EARTHQUAKE
32           FISH
33         ARTIST
34           RING
35       BROCCOLI
36    GRANDPARENT
37         MURDER
38       COMEDIAN
39         MUSCLE
40          SAUCE
41        SPARROW
42          ORGAN
43         LIZARD
44          EARTH
45           COKE
46         DOLLAR
47         DOCTOR
Name: Noun, dtype: object

In [49]:
def randomize_match_trials():
    # distribute the number of matching trials in each condition (e.g. COMP_1W)
    # there are 50 match trials and 50 mismatch trials in each condition
    # there must be at least 2 matching trials in each 5-trial block
    # there are 20 blocks in each condition in total
    # divide 50 into 20 sets, where there can't be more than 3 in each set
    while True:
        match_num = [random.choice([0,1,2]) for i in range(20)]
        if sum(match_num)==10:
            return([match_num[i]+2 for i in range(len(match_num))])

In [50]:
randomize_match_trials()

[4, 3, 2, 2, 3, 2, 2, 3, 2, 2, 2, 4, 2, 2, 4, 2, 3, 2, 2, 2]

In [101]:
orders_idx = [1, 2, 3, 4]
repeated_order = orders_idx*6
# balance the condition order
all_orders = list(itertools.permutations(orders_idx))
for i in range(len(all_orders)):
    all_orders[i] = list(all_orders[i][:])+[repeated_order[i]]

all_orders

[[1, 2, 3, 4, 1],
 [1, 2, 4, 3, 2],
 [1, 3, 2, 4, 3],
 [1, 3, 4, 2, 4],
 [1, 4, 2, 3, 1],
 [1, 4, 3, 2, 2],
 [2, 1, 3, 4, 3],
 [2, 1, 4, 3, 4],
 [2, 3, 1, 4, 1],
 [2, 3, 4, 1, 2],
 [2, 4, 1, 3, 3],
 [2, 4, 3, 1, 4],
 [3, 1, 2, 4, 1],
 [3, 1, 4, 2, 2],
 [3, 2, 1, 4, 3],
 [3, 2, 4, 1, 4],
 [3, 4, 1, 2, 1],
 [3, 4, 2, 1, 2],
 [4, 1, 2, 3, 3],
 [4, 1, 3, 2, 4],
 [4, 2, 1, 3, 1],
 [4, 2, 3, 1, 2],
 [4, 3, 1, 2, 3],
 [4, 3, 2, 1, 4]]

In [243]:
a = np.array([1,2,3])>np.array([3,3,3])
False in a

True

In [244]:
sum(np.array([1,2,3]))

6

In [253]:
def randomize_yesno_trials(constraints):
    constraints = np.array(constraints)
    while True:
        yes_num = np.array([random.choice([0,1,2,3]) for i in range(8)])
        if sum(yes_num)==12 and not False in (constraints>=yes_num):
            return([yes_num[i] for i in range(len(yes_num))])
randomize_yesno_trials([3,3,3,3,3,3,3,0])
#[1,1,1,1,1,1,1,1]

[2, 1, 2, 2, 2, 3, 0, 0]

In [266]:
material_order = ["L1-S1", "L1-S2", "L2-S1", "L2-S2"]
all_orders = list(itertools.permutations(material_order))
for subjn, order in zip(list(range(1, 25)), all_orders):
    print(subjn, order)

1 ('L1-S1', 'L1-S2', 'L2-S1', 'L2-S2')
2 ('L1-S1', 'L1-S2', 'L2-S2', 'L2-S1')
3 ('L1-S1', 'L2-S1', 'L1-S2', 'L2-S2')
4 ('L1-S1', 'L2-S1', 'L2-S2', 'L1-S2')
5 ('L1-S1', 'L2-S2', 'L1-S2', 'L2-S1')
6 ('L1-S1', 'L2-S2', 'L2-S1', 'L1-S2')
7 ('L1-S2', 'L1-S1', 'L2-S1', 'L2-S2')
8 ('L1-S2', 'L1-S1', 'L2-S2', 'L2-S1')
9 ('L1-S2', 'L2-S1', 'L1-S1', 'L2-S2')
10 ('L1-S2', 'L2-S1', 'L2-S2', 'L1-S1')
11 ('L1-S2', 'L2-S2', 'L1-S1', 'L2-S1')
12 ('L1-S2', 'L2-S2', 'L2-S1', 'L1-S1')
13 ('L2-S1', 'L1-S1', 'L1-S2', 'L2-S2')
14 ('L2-S1', 'L1-S1', 'L2-S2', 'L1-S2')
15 ('L2-S1', 'L1-S2', 'L1-S1', 'L2-S2')
16 ('L2-S1', 'L1-S2', 'L2-S2', 'L1-S1')
17 ('L2-S1', 'L2-S2', 'L1-S1', 'L1-S2')
18 ('L2-S1', 'L2-S2', 'L1-S2', 'L1-S1')
19 ('L2-S2', 'L1-S1', 'L1-S2', 'L2-S1')
20 ('L2-S2', 'L1-S1', 'L2-S1', 'L1-S2')
21 ('L2-S2', 'L1-S2', 'L1-S1', 'L2-S1')
22 ('L2-S2', 'L1-S2', 'L2-S1', 'L1-S1')
23 ('L2-S2', 'L2-S1', 'L1-S1', 'L1-S2')
24 ('L2-S2', 'L2-S1', 'L1-S2', 'L1-S1')

In [270]:
not (False in [True, True])

True